version: '3.4'

services:
  proxy:
    image: traefik
    ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - ./servers.toml:/servers.toml
      - ./traefik_logs:/traefik_logs
    container_name:traefik
      
volumes:
  traefik_logs:

